---
argument_specs:
  main:
    version_added: 1.0.0
    short_description: A role to create/delete the necessary Azure infrastructure for an Azurerm remote backend for Terraform.
    description:
      - A role to ensure that the necessary Azure infrastructure is present/absent for an Azurerm remote backend for Terraform.
      - When O(azurerm_backend_operation=create), the role ensures that a resource group, a storage account and a container are present and optionally
        assigns the 'Storage Blob Data Contributor' role for the specified container to the service principal provided by the user.
      - When O(azurerm_backend_operation=delete), the role will force deletion of the resource group.
    options:
      azurerm_backend_operation:
        description:
          - Whether to create or delete the infrastructure for the azurerm Terraform backend.
          - When set to V(delete), the resource group will be deleted with all attached resources.
        choices:
          - create
          - delete
        default: create
      azurerm_backend_resource_group_name:
        description:
          - The name of the resource group to create/delete.
        required: true
      azurerm_backend_location:
        description:
          - Azure location for the resource group. Required when creating a new resource group.
      azurerm_backend_storage_account_name:
        description:
          - The name of the storage account name to be created.
          - When not specified and if none is existing from the resource group, the role will create
            a new one with generated name.
      azurerm_backend_storage_account_type:
        description:
          - Type of storage account. Required when creating a storage account.
        type: str
        choices:
          - Premium_LRS
          - Standard_GRS
          - Standard_LRS
          - Standard_RAGRS
          - Standard_ZRS
          - Premium_ZRS
          - Standard_RAGZRS
          - Standard_GZRS
        default: Standard_LRS
      azurerm_backend_container_name:
        description:
          - The Name of the Storage Container to create within the Storage Account.
          - Required when O(azurerm_backend_operation=create).
      azurerm_backend_service_principal_id:
        description:
          - The service principal Id used by Terraform to push Terraform state to the container.
          - The role will assign the Storage Blob Data Contributor U(https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor) role for the specified container to this service principal.
