---
argument_specs:
  main:
    version_added: 1.0.0
    short_description: A role to handle the base64 encoding or decoding of a terraform plan file using cloud.terraform.plan_stash module.
    description:
      - A role to handle the base64 encoding or decoding of a terraform plan file using cloud.terraform.plan_stash module.
      - Perform base64-encoding of a terraform plan file and saves it into playbook execution stats similar to M(ansible.builtin.set_stats) module.
      - Perform base64-decoding of a terraform plan file from a variable defined into ansible facts and write them into a file specified by the user.
    options:
      plan_stash_operation:
        description:
          - Whether to base64-encode the terraform plan file and save it into ansible stats or base64-decode data from variable to create a terraform plan file.
        choices:
          - stash
          - load
        required: true
        type: str
      plan_stash_plan_file_path:
        description:
          - The path to the terraform plan file.
          - This will be used for both encoding/decoding plan file depending on the value set into plan_stash_operation.
        required: true
        type: str
      plan_stash_var_name:
        description:
          - -When O(state=stash), this parameter defines the variable name to be set into stats.
          - When O(state=load), this parameter defines the variable from ansible facts containing the base64-encoded data of the terraform plan file.
          - Variables must start with a letter or underscore character, and contain only letters, numbers and underscores.
        required: false
        type: str
