---
- name: Test the cloud.terraform_ops.module_plan_stash role 'stash' functionality
  hosts: localhost
  gather_facts: true
  tasks:

    - name: check if tempdir from earlier playbook in workflow exists
      debug:
        msg: "{{ tfdir.path }}"
      ignore_errors: true

    - name: Create temporary directory to run terraform configuration
      ansible.builtin.tempfile:
        state: directory
      register: tfdir

    - name: Load the Terraform plan file
      vars:
        terraform_plan_file: "{{ tfdir.path }}/loaded_plan.tfplan"
      block:

        - name: Load the terraform plan file from variable "{{ module_plan_stash_var_name | default('terraform_plan') }}" into file "{{ terraform_plan_file }}"
          ansible.builtin.include_role:
            name: cloud.terraform_ops.module_plan_stash
          vars:
            module_plan_stash_operation: load
            module_plan_stash_plan_file_path: "{{ terraform_plan_file }}"
            module_plan_stash_tf_project_path: "{{ tfdir.path }}"

      always:
        - name: Delete temporary directory
          ansible.builtin.file:
            state: absent
            path: "{{ tfdir.path }}"