---
- name: Test the cloud.terraform_ops.module_plan_stash role
  hosts: localhost
  gather_facts: true
  tasks:

    - name: Create temporary directory to run terraform configuration
      ansible.builtin.tempfile:
        # suffix: '.tf'
        state: directory
      register: tfdir

    - name: Stash the Terraform plan file
      vars:
        terraform_plan_file: "{{ tfdir.path }}/generated_plan.tfplan"
      block:
        - name: Download terraform configuration
          uri:
            dest: "{{ tfdir.path }}/main.tf"
            url: "{{ terraform_config_url }}"

        # - name: Download terraform plan file original_plan.tfplan
        #   uri:
        #     dest: "{{ tfdir.path }}/original_plan.tfplan"
        #     url: "{{ terraform_config_url }}"

        - name: Stash the Terraform plan file
          ansible.builtin.include_role:
            name: cloud.terraform_ops.module_plan_stash
          vars:
            module_plan_stash_operation: stash
            module_plan_stash_generate_plan_file: true
            module_plan_stash_plan_file_path: "{{ terraform_plan_file }}"
            module_plan_stash_tf_project_path: "{{ tfdir.path }}"

      always:

        - name: List all files in tempdir
          command: "ls {{ tfdir.path }}"
          register: dir_out

        - name: List all files in tempdir
          debug:
            var: dir_out.stdout_lines

        # - name: Delete temporary directory
        #   ansible.builtin.file:
        #     state: absent
        #     path: "{{ tfdir.path }}"