---
- name: Decode stash plan and create a plan file
  copy:
    dest: "{{ module_plan_stash_plan_file_path }}"
    content: "{{ terraform_plan | b64decode }}"

- name: Apply terraform plan
  cloud.terraform.terraform:
    project_path: "{{ module_plan_stash_tf_project_path}}"
    plan_file: "{{ module_plan_stash_plan_file_path }}"
    force_init: true
    state: present
