---
- name: Load the terraform plan file from variable "{{ module_plan_stash_var_name | default('terraform_plan') }}" into file "{{ module_plan_stash_plan_file_path }}"
  cloud.terraform.plan_stash:
    path: "{{ module_plan_stash_plan_file_path }}"
    state: load
    var_name: "{{ module_plan_stash_var_name | default(omit) }}" # default value terraform_plan is used by module itself, not required to specify here
    binary_data: "{{ binary_data | default(omit) }}"
  ignore_errors: true
  # no_log: true

- debug: msg="removed force_init from load.yml"
- debug: msg="added init_reconfigure to load.yml"
- name: Apply terraform plan
  cloud.terraform.terraform:
    project_path: "{{ module_plan_stash_tf_project_path}}"
    plan_file: "{{ module_plan_stash_plan_file_path }}"
    # force_init: true
    init_reconfigure: true
    state: present
