---
- name: Delete S3 bucket
  amazon.aws.s3_bucket:
    name: "{{ aws_s3backend_bucket_name }}"
    state: absent
    force: true

- name: Delete dynamodb table
  community.aws.dynamodb_table:
    state: absent
    name: "{{ aws_s3backend_dynamodb_table_name }}"
    wait: true
  when: aws_s3backend_dynamodb_table_name is defined

- name: Delete the policy attached to the user/role/group
  amazon.aws.iam_policy:
    iam_type: "{{ aws_s3backend_iam_type }}"
    iam_name: "{{ aws_s3backend_iam_name }}"
    policy_name: "{{ aws_s3backend_policy_name }}"
    state: absent
  when: aws_s3backend_iam_type is defined

- name: Delete IAM user
  amazon.aws.iam_user:
    name: "{{ aws_s3backend_iam_name }}"
    state: absent
  when:
    - aws_s3backend_delete_iam_resource | bool
    - aws_s3backend_iam_type | default('') == "user"

- name: Delete IAM role
  amazon.aws.iam_role:
    name: "{{ aws_s3backend_iam_name }}"
    state: absent
  when:
    - aws_s3backend_delete_iam_resource | bool
    - aws_s3backend_iam_type | default('') == "role"

- name: Delete IAM group
  amazon.aws.iam_group:
    name: "{{ aws_s3backend_iam_name }}"
    state: absent
  when:
    - aws_s3backend_delete_iam_resource | bool
    - aws_s3backend_iam_type | default('') == "group"
