---
- name: Gather IAM Role info
  amazon.aws.iam_role_info:
    name: "{{ aws_s3backend_iam_name }}"
  register: existing_roles

- name: Create Role with policy
  amazon.aws.iam_role:
    name: "{{ aws_s3backend_iam_name }}"
    assume_role_policy_document: "{{ lookup('file', 'role-policy.json') }}"
    state: present
  when: existing_roles.iam_roles | length == 0

- name: Apply policy to Role
  amazon.aws.iam_policy:
    iam_type: "role"
    iam_name: "{{ aws_s3backend_iam_name }}"
    policy_name: "{{ aws_s3backend_policy_name }}"
    policy_json: "{{ lookup('template', 'policy.json.j2') }}"
    state: present
